In [3]:
import torch
x = torch.arange(12)
x.numel()
x[0] = 1



In [11]:
x[0] =  10

print(x.numel())

12


In [13]:
x.numel()
x

tensor([10,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
X = x.reshape


In [20]:
x
torch.exp(x)




tensor([2.2026e+04, 2.7183e+00, 7.3891e+00, 2.0086e+01, 5.4598e+01, 1.4841e+02,
        4.0343e+02, 1.0966e+03, 2.9810e+03, 8.1031e+03, 2.2026e+04, 5.9874e+04])

In [21]:
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)


(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [22]:
X,Y

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[2., 1., 4., 3.],
         [1., 2., 3., 4.],
         [4., 3., 2., 1.]]))

In [25]:
X==Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [26]:
import os
os.makedirs(os.path.join('..', 'data'), exist_ok=True)
data_file = os.path.join('..', 'data', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n') # 列名
    f.write('NA,Pave,127500\n') # 每⾏表⽰⼀个数据样本
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

In [27]:
import pandas as pd
data = pd.read_csv(data_file)
print(data)

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000


In [29]:
inputs, outputs = data.iloc[:, 0:2], data.iloc[:, 2]
inputs = inputs.fillna(inputs.mean())
print(inputs)

inputs = pd.get_dummies(inputs, dummy_na=True)
X, y = torch.tensor(inputs.values), torch.tensor(outputs.values)
X, y

   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN


C:\Users\dell\AppData\Local\Temp/ipykernel_12096/2751762312.py:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  inputs = inputs.fillna(inputs.mean())


(tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500, 106000, 178100, 140000]))

In [39]:
inputs.values
outputs.values

array([127500, 106000, 178100, 140000], dtype=int64)

In [45]:
X

tensor([[3., 1., 0.],
        [2., 0., 1.],
        [4., 0., 1.],
        [3., 0., 1.]], dtype=torch.float64)

In [48]:
y

data

tensor([127500, 106000, 178100, 140000])

In [55]:
for a in data.loc():
    print(a)

NumRooms       NaN
Alley         Pave
Price       127500
Name: 0, dtype: object
NumRooms       2.0
Alley          NaN
Price       106000
Name: 1, dtype: object
NumRooms       4.0
Alley          NaN
Price       178100
Name: 2, dtype: object
NumRooms       NaN
Alley          NaN
Price       140000
Name: 3, dtype: object


KeyError: 4

In [67]:
data.Alley
data.index
list(data)

['NumRooms', 'Alley', 'Price']

In [59]:
data

NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000

In [72]:
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
A
0

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [71]:
A.cumsum(axis=0)


tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])

In [86]:
num_dic = data.isna().sum().to_dict()
max_key =max(num_dic, key = num_dic.get)
max_key
num_dic.get

<function dict.get(key, default=None, /)>

In [89]:
del data[max_key]

data

KeyError: 'Alley'

In [97]:
data

data
data.

RangeIndex(start=0, stop=4, step=1)

In [100]:
data.head()



NumRooms   Price
0       NaN  127500
1       2.0  106000
2       4.0  178100
3       NaN  140000

In [101]:
import numpy

In [102]:
%matplotlib inline
import numpy as np
from IPython import display
from d2l import torch as d2l



ModuleNotFoundError: No module named 'd2l'

In [103]:
%matplotlib inline
import numpy as np
from IPython import display
from d2l import torch as d2l

ModuleNotFoundError: No module named 'd2l'

In [1]:
%matplotlib inline
import numpy as np
from IPython import display
from d2l import torch as d2l

ModuleNotFoundError: No module named 'torchvision'

In [2]:
from d2l import torch as d2l


In [1]:
x = torch.arange(4.0)


NameError: name 'torch' is not defined